sonar.projectKey=ISCOUTB_AS_202620_Verifacts
sonar.organization=isco-utb
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

#sonarclouconfiguracion
sonar.exclusions=**/render.yaml
